### ISSUE TITLE
Проработать архитектуру клиента

### ISSUE THREAD

**Issue by dlastochkin** [dlastochkin/ProgrammingSchool#4]
1. Определить кто будет заниматься GUI, кто логикой и написать в комментарии к этой задаче
2. Нарисовать дизайн-проект интерфейса и сложить его по пути CChat/Client/Doc
3. Продумать взаимодействие между GUI и логической частью
4. Создать и добавить .h файл с описанием клиента

**Comment by Rokfessor** [comment]
Дизайн-проект интерфейса: Анастасия Ремезова, Ишбулатов Максим.
Взаимодействие между GUI и логикой: Александр Лой, Алексей Новоженин.
.h файл с описанием клиента: Лаврухин Михаил, Ишбулатов Максим.

**Comment by dlastochkin** [comment]
Максим, в первом пункте я имел ввиду разделение задач реализации, а не предварительного проектирования. Напиши, пожалуйста, кто будет заниматься разработкой класса с GUI, а кто разработкой логической части.

**Comment by Rokfessor** [comment]
Разработка GUI - Новоженин, Лой, Ремезова
Разработка логической части - Ишбулатов, Лаврухин

**Comment by dlastochkin** [comment]
Ок. Можете заниматься проектированием.

**Comment by dlastochkin** [comment]
Максим, необходимо переместить дизайн-проект в директорию **/CChat/Client/Doc/**

**Comment by Rokfessor** [comment]
Понял, а .h файл с описанием клиента куда заливать?

**Comment by dlastochkin** [comment]
/CChat/Client/Src/CChatClient.h
/CChat/Client/Src/CChatClientGUI.h

**Comment by dlastochkin** [comment]
Архитектуру обсудили. Можно приступать к реализации. Максим, создай соответствующие задачи.
