### ISSUE TITLE
Проработать архитектуру сервера

### ISSUE THREAD

**Issue by dlastochkin** [dlastochkin/ProgrammingSchool#5]
1. Определить кто будет заниматься GUI, кто логикой и написать в комментарии к этой задаче
2. Нарисовать дизайн-проект интерфейса и сложить его по пути CChat/Server/Doc
3. Продумать взаимодействие между GUI и логической частью
4. Создать и добавить .h файл с описанием клиента

**Comment by JohnRamRu** [comment]
#5. Add GUI/Logic groups
1. GUI: Голчина, Комлев.
2. Логика: Агеев, Радаев.

**Comment by dlastochkin** [comment]
Женя, комментарий вида "#5. Add GUI/Logic groups" имеет смысл оставлять только при коммите. И еще вопрос: а Егор чем занимается?

**Comment by JohnRamRu** [comment]
Окей.
Новый список подгрупп
1)GUI: Голчина, Комлев.
2) Логика: Агеев, Радаев, Ежов.

**Comment by dlastochkin** [comment]
Ок. Можете заниматься проектированием.

**Comment by dlastochkin** [comment]
Женя, ты сложил дизайн-проект сервера в бранч клиента. Необходимо это исправить. Для этого:
1. Удали папку **/CChat/Doc/Server/** и закомить изменения с сообщением "#5. Remove server design from Client branch"
2. В GitHub Desktop смени бранч на Server
![change_branch](https://user-images.githubusercontent.com/48003172/54100626-2fca4b00-43e1-11e9-8115-10b44371564a.png)
3. Cоздай папку **/CChat/Server/Doc/**, закинь в нее дизайн-проект и закомить с сообщением "#5. Add server design to Server branch"

**Comment by JohnRamRu** [comment]
Ой, правда.

Вечером поправлю.

**Comment by dlastochkin** [comment]
Архитектуру обсудили. Можно приступать к реализации. Женя, создай соответствующие задачи.
