### ISSUE TITLE
Продумать работу трассы

### ISSUE THREAD

**Issue by dlastochkin** [dlastochkin/ProgrammingSchool#6]

**Comment by Korinin38** [comment]
Trace requirements:
enum mType = {EVENT, WARNING, ERROR}
1) messageTrace - private class including:
mType type;
QString body;
QTime time;
QDate date;

2) listTrace - list of messageTrace;

3) listImport() func:
Imports listTrace from file;

4) trace(QString ms, mType tp) func - body, message type:
Converts ms into messageTrace and add it to listTrace;

5) transmit(messageTrace mss) slot - message:
Updates all (console, file, QTextEdit?) streams by adding mss to it;
6) ...

**Comment by Korinin38** [comment]
Where is Trace.h emplacement?
/CChat/Common/Trace.h?

**Comment by dlastochkin** [comment]
Артём, можно по русски)
Путь: **/CChat/Common/Trace/CChatTrace.h**
Бранч: **master**

**Comment by Korinin38** [comment]
а, ладно

**Comment by dlastochkin** [comment]
По тех. заданию:

mType -> MessageSeverity
messageTrace -> TraceMessage

Для даты и времени: [QDateTime](https://doc.qt.io/qt-5/qdatetime.html) time;

Класс трассы: CChatTrace
Методы:

- void add(QString message, MessageSeverity severity)
- void addDestination(TraceDestination destination)
- QList&lt;TraceMessage&gt; getMessages()
- продумать самостоятельно

Поля:
- [QList&lt;TraceDestination&gt;](https://doc.qt.io/qt-5/qlist.html) destinations

Класс AbstractTraceDestination:

- abstract void putMessage(TraceMessage message) = 0;
- abstract QList&lt;TraceMessage&gt; loadMessages() = 0;

Наследники:

- FileTraceDestination(QString destinationFile)
- ListTraceDestination(QList&lt;TraceMessage&gt; destinationList)

**Comment by dlastochkin** [comment]
Это по логике. Над интерфейсной частью подумай самостоятельно, учитывая приведенное API.

**Comment by Korinin38** [comment]
> void addDestination(TraceDestination destination)
> Класс AbstractTraceDestination:

Я понимаю, что:
- Сам класс называется TraceDestination, в нём все методы абстрактны.
- Абстрактный метод = виртуальный метод

Поправьте, если не прав

**Comment by Korinin38** [comment]
> QList<TraceMessage> getMessages()

Что делает данный метод? Выдаёт все сообщения в QList и возвращает его экземпляр?
В таком случае, если сообщения хранятся внутри класса в QList, данный метод возвращает копию этого листа? Для чего необходим этот метод?

**Comment by dlastochkin** [comment]
> Я понимаю, что:
>Сам класс называется TraceDestination, в нём все методы абстрактны.
>Абстрактный метод = виртуальный метод
>Поправьте, если не прав

Все правильно. Наследники этого класса пишут трассу в файл (FileTraceDestination) и в список (ListTraceDestination).

> Что делает данный метод? Выдаёт все сообщения в QList и возвращает его экземпляр?
> В таком случае, если сообщения хранятся внутри класса в QList, данный метод возвращает копию этого листа? Для чего необходим этот метод?

Да, все верно. Этот метод нужен для заполнения GUI. Т.е. ты передаешь экземпляр класса CChatTrace в виджет отображения трассы, виджет вызывает этот метод и строит таблицу.
